/**
 * Data Daemon — continuously generates battle + UI data for the Kafka pipeline.
 * Battle pool: 8 concurrent workers (lightweight, for live demo).
 * UI pool: 3 concurrent workers, each generating UI events.
 * Usage: node data_daemon.js
 */
const { Battle, Teams, Dex } = require('pokemon-showdown');
const { Kafka } = require('kafkajs');
const fs = require('fs');
const path = require('path');

const BATTLE_WORKERS = 8;
const UI_WORKERS = 3;
const KAFKA_BROKER = process.env.KAFKA_BROKER || "100.107.105.99:9092";
const BATTLE_OUTPUT_DIR = path.join(__dirname, '..', 'battle_logs');

// ── Kafka ──
const kafka = new Kafka({
  brokers: [KAFKA_BROKER],
  connectionTimeout: 5000,
  requestTimeout: 10000,
  retry: { retries: 3 },
});
const producer = kafka.producer();

function ts() { return new Date().toISOString(); }
async function send(topic, key, value) {
  value.timestamp = ts();
  await producer.send({ topic, messages: [{ key: String(key || ""), value: JSON.stringify(value) }] });
}

// ── Game data ──
const allMoves = Dex.moves.all().filter(m =>
  (m.category === "Physical" || m.category === "Special") && m.basePower > 0 && m.num > 0
);
const allSpecies = Dex.species.all().filter(s => s.num > 0 && !s.name.startsWith("MissingNo") && !s.isNonstandard);
const allAbilities = Dex.abilities.all().filter(a => a.num > 0);
const allItems = Dex.items.all().filter(i => i.num > 0 && !i.isBerry && !i.isGem && !i.name.includes("Drive") && !i.name.includes("Memory"));

const NATURES = ["Hardy","Lonely","Brave","Adamant","Naughty","Bold","Docile","Relaxed","Impish","Lax","Timid","Hasty","Serious","Jolly","Naive","Modest","Mild","Quiet","Bashful","Rash","Calm","Gentle","Sassy","Careful","Quirky"];
const NATURE_NAMES = ["Adamant","Jolly","Modest","Timid","Bold","Impish","Calm","Careful"];
const PLAYERS = ["Ash","Serena","Leon","Cynthia","Red","Blue","May","Dawn","Brock","Misty"];
const PAGES = ["/","/matchmaking","/teams","/stats","/data"];
const CLICKS = ["btn_confirm","btn_switch","btn_move_select","btn_join_match","btn_join_bot","btn_save_team","nav_matchmaking","nav_teams","nav_stats","nav_data"];

// ── Smogon meta cache (loaded from JSON, generated by scripts/py/export_smogon_meta.py) ──
let _metaCache = null;
function loadMeta() {
  if (_metaCache) return _metaCache;
  try {
    const fs = require('fs');
    const path = require('path');
    const p = path.join(__dirname, '..', 'data', 'smogon_meta.json');
    if (fs.existsSync(p)) {
      _metaCache = JSON.parse(fs.readFileSync(p, 'utf-8'));
      console.log(`[daemon] Loaded Smogon meta: ${_metaCache.species?.length || 0} species`);
    }
  } catch (e) { console.warn('[daemon] Failed to load smogon_meta.json:', e.message); }
  return _metaCache || { species: [] };
}

// Weighted random pick from [{name, weight}, ...]
function weightedPick(items, weightKey) {
  if (!items || !items.length) return null;
  const total = items.reduce((s, it) => s + Math.max(0.001, it[weightKey] || 0), 0);
  let r = Math.random() * total, cum = 0;
  for (const it of items) {
    cum += Math.max(0.001, it[weightKey] || 0);
    if (cum >= r) return it;
  }
  return items[items.length - 1];
}

// Lookup: Smogon name → Showdown species ID
function smogonToSpecies(smogonName) {
  const norm = smogonName.toLowerCase().replace(/[^a-z0-9]/g, '');
  for (const sp of allSpecies) {
    if (sp.name.toLowerCase().replace(/[^a-z0-9]/g, '') === norm) return sp;
  }
  return Dex.species.get(smogonName) || null;
}

// ── Team builder (Smogon-weighted) ──
function randomTeam() {
  const meta = loadMeta();
  const speciesPool = meta.species || [];
  const team = [];
  const picked = new Set();
  const count = 3;  // fixed 3, like VS Bot

  for (let attempt = 0; attempt < 20 && team.length < count; attempt++) {
    const pick = weightedPick(speciesPool, 'weight');
    if (!pick) continue;
    const sp = smogonToSpecies(pick.name);
    if (!sp || picked.has(sp.num)) continue;
    picked.add(sp.num);

    // ── Moves: top 10 Smogon, filtered to learnable, weighted pick 4 ──
    const moves = [];
    const smogonMoves = pick.moves || [];
    const learnablePool = [];
    for (const sm of smogonMoves) {
      const mv = Dex.moves.get(sm.name);
      if (mv && mv.num > 0 && Dex.data.Learnsets[sp.id]?.learnset?.[sm.name]) {
        learnablePool.push({ name: sm.name, usage: sm.usage });
      }
    }
    for (let i = 0; i < 4 && learnablePool.length > 0; i++) {
      const mp = weightedPick(learnablePool, 'usage');
      if (mp) {
        moves.push(mp.name);
        learnablePool.splice(learnablePool.indexOf(mp), 1);
      }
    }
    // Fallback: random learnable moves
    if (moves.length < 4) {
      const fallback = [];
      for (const m of allMoves) {
        if (Dex.data.Learnsets[sp.id]?.learnset?.[m.id] && !moves.includes(m.name)) fallback.push(m.name);
      }
      while (moves.length < 4 && fallback.length > 0) {
        const idx = Math.floor(Math.random() * fallback.length);
        moves.push(fallback.splice(idx, 1)[0]);
      }
    }

    // ── Ability: top 10 Smogon, weighted pick 1 ──
    let ability = 'No Ability';
    const smogonAbilities = pick.abilities || [];
    const abilityPool = [];
    for (const ab of smogonAbilities) {
      const a = Dex.abilities.get(ab.name);
      if (a && a.num > 0) abilityPool.push({ name: a.name, usage: ab.usage });
    }
    const abPick = weightedPick(abilityPool, 'usage');
    if (abPick) ability = abPick.name;

    // ── Item: top 10 Smogon, weighted pick 1 ──
    let item = '';
    const smogonItems = pick.items || [];
    const itemPool = [];
    for (const it of smogonItems) {
      const i = Dex.items.get(it.name);
      if (i && i.num > 0) itemPool.push({ name: i.name, usage: it.usage });
    }
    const itPick = weightedPick(itemPool, 'usage');
    if (itPick) item = itPick.name;

    // ── Spread: top 10 Smogon, weighted pick 1 ──
    let nature = 'Adamant';
    let evs = { hp: 0, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 };
    const smogonSpreads = pick.spreads || [];
    const spPick = weightedPick(smogonSpreads, 'usage');
    if (spPick) {
      const spNat = spPick.nature || 'Adamant';
      const match = NATURES.find(n => n.toLowerCase() === spNat.toLowerCase());
      if (match) nature = match;
      const evParts = (spPick.evs || '0/252/0/0/4/252').split('/').map(Number);
      if (evParts.length === 6) {
        evs = { hp: evParts[0], atk: evParts[1], def: evParts[2], spa: evParts[3], spd: evParts[4], spe: evParts[5] };
      }
    }

    team.push({
      name: "", species: sp.name,
      ability, item, moves: moves.slice(0, 4),
      nature,
      evs, ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
      level: 50,
    });
  }
  return team;
}

function teamToInit(team) {
  return team.map(p => ({
    speciesID: Dex.species.get(p.species).num,
    moves: p.moves.map(m => Dex.moves.get(m).num),
    item: Dex.items.get(p.item).num,
    ability: Dex.abilities.get(p.ability).num,
    nature: NATURES.indexOf(p.nature),
    level: 50,
    evs: p.evs || { hp: 0, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 },
    ivs: p.ivs || { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
  }));
}

// ── Battle worker ──
let battleCount = 0;
let uiCount = 0;

// Write local output JSON for ADS importer (battle_importer.py reads these)
function writeOutput(bid, turn, battle) {
  try {
    const dir = path.join(BATTLE_OUTPUT_DIR, bid, 'output');
    fs.mkdirSync(dir, { recursive: true });

    function buildSide(side) {
      return {
        side: side === battle.p1 ? 0 : 1,
        pokemons: (side?.pokemon || []).map((p, i) => {
          if (!p) return { fainted: true, slot: i, speciesId: 0, hp: 0, maxHp: 1 };
          const sp = Dex.species.get(p.species);
          return {
            speciesId: sp?.num || 0,
            hp: p.hp || 0,
            maxHp: p.maxhp || 1,
            fainted: p.fainted || p.hp <= 0,
            abilityId: p.ability ? (Dex.abilities.get(p.ability)?.num || 0) : 0,
            itemId: p.item ? (Dex.items.get(p.item)?.num || 0) : 0,
            moves: (p.moveSlots || []).map(ms => ({
              id: ms?.move ? (Dex.moves.get(ms.move)?.num || 0) : 0,
            })),
            slot: i,
          };
        }),
        active: side?.active?.[0]?.position ?? 0,
      };
    }

    const state = {
      turn,
      battle: {
        sides: [buildSide(battle.p1), buildSide(battle.p2)],
      },
    };

    const filename = turn === 0 ? 'output_0.json' :
      battle.ended ? 'output_final.json' : `output_${turn}.json`;
    const tmp = path.join(dir, filename + '.tmp');
    const dest = path.join(dir, filename);
    fs.writeFileSync(tmp, JSON.stringify(state));
    fs.renameSync(tmp, dest);
  } catch (e) { /* silent — best effort */ }
}

async function battleWorker(id) {
  while (true) {
    try {
      // Assign real player IDs for this battle
      const p1 = PLAYERS[Math.floor(Math.random() * PLAYERS.length)];
      let p2 = PLAYERS[Math.floor(Math.random() * PLAYERS.length)];
      while (p2 === p1) p2 = PLAYERS[Math.floor(Math.random() * PLAYERS.length)];
      const bid = `b_${id}_${Date.now().toString(36)}`;
      const sid = `sess_${p1}_${p2}_${Date.now().toString(36)}`;
      const teamA = randomTeam();
      const teamB = randomTeam();
      battleCount++;
      const battle = new Battle({ formatid: "gen9customgame", seed: [42, 1, 3, 7], debug: false });
      battle.join("p1", p1, p1, Teams.pack(teamA));
      battle.join("p2", p2, p2, Teams.pack(teamB));
      battle.choose("p1", "team 1");
      battle.choose("p2", "team 1");
      writeOutput(bid, 0, battle);

      await send("battle.logs", bid, {
        event: "battle_init",
        battle_id: bid, session_id: sid,
        player_a: p1, player_b: p2,
        data: {
          battle_id: bid, session_id: sid,
          player_a: p1, player_b: p2, opponent_type: "bot",
          side_a: teamToInit(teamA),
          side_b: teamToInit(teamB),
        }
      });

      let turn = 0;
      while (!battle.ended && turn < 20) {
        turn++;
        battle.choose("p1", "move " + (Math.floor(Math.random() * 4) + 1));
        battle.choose("p2", "move " + (Math.floor(Math.random() * 4) + 1));

        const sideA = battle.p1?.active[0];
        const sideB = battle.p2?.active[0];
        const spA = sideA?.species ? Dex.species.get(sideA.species) : null;
        const spB = sideB?.species ? Dex.species.get(sideB.species) : null;
        await send("battle.logs", bid, {
          event: "turn_executed",
          battle_id: bid, session_id: sid, turn,
          player_a: p1, player_b: p2,
          data: {
            battle_id: bid, session_id: sid, turn,
            [p1]: { hp: sideA?.hp || 0, maxhp: sideA?.maxhp || 1, fainted: sideA?.fainted || false, speciesId: spA?.num||0, speciesName: spA?.name||'?' },
            [p2]: { hp: sideB?.hp || 0, maxhp: sideB?.maxhp || 1, fainted: sideB?.fainted || false, speciesId: spB?.num||0, speciesName: spB?.name||'?' },
          }
        });

        // Parse damage/faint/switch from Showdown log lines
        // Format: |move|ATTACKER|MOVE|TARGET   then   |-damage|TARGET|CUR/MAX
        const from = Math.max(0, battle.log.length - 50);
        let lastMove = null;
        for (let i = from; i < battle.log.length; i++) {
          const line = battle.log[i];
          // Track move from |move|POKEMON|NAME|TARGET
          if (line.startsWith("|move|")) {
            const p = line.split("|");
            lastMove = { name: p[3] || "?", attacker: p[2] || "?" };
          }
          // Showdown: |-damage|POKEMON|CUR/MAX[ fnt]
          if (line.startsWith("|-damage|")) {
            const p = line.split("|");
            const targetPokemon = p[2] || "?";
            const sideIsP1 = targetPokemon.startsWith("p1");
            const targetPlayer = sideIsP1 ? p1 : p2;
            const hpField = (p[3] || "").trim();
            const isFaint = hpField.includes("fnt");
            const hpParts = hpField.split(" ")[0].split("/");
            const curHp = parseInt(hpParts[0]) || 0;
            const parsedMax = parseInt(hpParts[1]) || 0;
            const active = sideIsP1 ? sideA : sideB;
            const maxHp = active?.maxhp || parsedMax || 1;
            const prevHp = active?._prevHp;
            const dmg = prevHp != null ? prevHp - curHp : (maxHp - curHp);
            if (active) active._prevHp = curHp;

            if (dmg > 0 || isFaint) {
              const dmgTarget = (p[2]||'').split(':').pop()||'?';
              const dmgSp = Dex.species.get(dmgTarget);
              await send("battle.logs", bid, {
                event: "turn_damage",
                battle_id: bid, session_id: sid, turn,
                data: {
                  battle_id: bid, session_id: sid, turn,
                  target_player: targetPlayer, damage: Math.max(dmg, 0),
                  maxhp: maxHp, curhp: curHp,
                  fainted: isFaint,
                  move_name: lastMove?.name || "unknown",
                  speciesId: dmgSp?.num||0, speciesName: dmgTarget,
                }
              });
            }
          } else if (line.startsWith("|faint|")) {
            const faintP1 = line.includes("p1");
            const faintParts = line.split("|");
            const faintedName = (faintParts[2]||'').split(':').pop()||'?';
            const faintSp = Dex.species.get(faintedName);
            await send("battle.logs", bid, {
              event: "turn_faint", battle_id: bid, session_id: sid, turn,
              data: { battle_id: bid, session_id: sid, turn, player: faintP1 ? p1 : p2, speciesId: faintSp?.num||0, speciesName: faintedName }
            });
          } else if (line.startsWith("|switch|") || line.startsWith("|drag|")) {
            const swP1 = line.includes("p1");
            const swParts = line.split("|");
            const switchedName = (swParts[2]||'').split(',')[0].split(':').pop()||'?';
            const swSp = Dex.species.get(switchedName);
            await send("battle.logs", bid, {
              event: "turn_switch", battle_id: bid, session_id: sid, turn,
              data: { battle_id: bid, session_id: sid, turn, player: swP1 ? p1 : p2, reason: line.startsWith("|drag|") ? "forced" : "manual", speciesId: swSp?.num||0, speciesName: switchedName }
            });
          }
        }

        // Force switches
        for (const p of ["p1", "p2"]) {
          if (battle[p]?.activeRequest?.forceSwitch?.[0]) {
            const pokemon = battle[p]?.pokemon?.filter(pk => !pk.fainted && pk.position !== battle[p].active[0]?.position);
            if (pokemon?.length) battle.choose(p, "switch " + (pokemon[0].position + 1));
            else battle.choose(p, "pass");
          }
        }
      }

      const aRem = battle.p1?.pokemon?.filter(p => !p.fainted).length || 0;
      const bRem = battle.p2?.pokemon?.filter(p => !p.fainted).length || 0;
      let winner = null, result = "draw";
      if (aRem > 0 && bRem === 0) { winner = p1; result = "completed"; }
      else if (bRem > 0 && aRem === 0) { winner = p2; result = "completed"; }

      await send("battle.logs", bid, {
        event: "battle_result",
        battle_id: bid, session_id: sid,
        player_a: p1, player_b: p2, winner,
        data: {
          battle_id: bid, session_id: sid,
          player_a: p1, player_b: p2,
          result, winner, turns: turn,
          side_a_remaining: aRem, side_b_remaining: bRem,
        }
      });

      // Minimal cooldown — keep pipeline busy
      await new Promise(r => setTimeout(r, 100 + Math.random() * 200));
    } catch (e) {
      // silently retry next battle
      await new Promise(r => setTimeout(r, 200));
    }
  }
}

// ── UI worker ──
async function uiWorker(id) {
  // Each UI worker simulates a persistent player session
  const player = PLAYERS[id % PLAYERS.length];
  const sessionId = `ui_sess_${player}_${id}_${Date.now().toString(36)}`;
  while (true) {
    try {
      uiCount++;
      const r = Math.random();
      if (r < 0.2) {
        await send("player.ui.events", player, { event: "page_view", player_id: player, session_id: sessionId, data: { page: PAGES[Math.floor(Math.random() * PAGES.length)] } });
      } else if (r < 0.4) {
        await send("player.ui.events", player, { event: "ui_click", player_id: player, session_id: sessionId, data: { element: CLICKS[Math.floor(Math.random() * CLICKS.length)] } });
      } else if (r < 0.55) {
        await send("player.ui.events", player, { event: "player_state", player_id: player, session_id: sessionId, data: { from: "idle", to: ["matching", "battling", "teambuilding"][Math.floor(Math.random() * 3)] } });
      } else if (r < 0.7) {
        await send("player.ui.events", player, { event: "matchmaking_join", player_id: player, session_id: sessionId, data: { opponent_type: Math.random() < 0.5 ? "human" : "bot" } });
      } else if (r < 0.85) {
        await send("player.ui.events", player, { event: "session_start", player_id: player, session_id: sessionId, data: { player_id: player } });
      } else {
        const team = Array.from({ length: Math.floor(Math.random() * 4) + 3 }, () => {
          const sp = allSpecies[Math.floor(Math.random() * allSpecies.length)];
          return { speciesID: sp.num, moves: [], item: allItems[Math.floor(Math.random() * allItems.length)].num, ability: allAbilities[Math.floor(Math.random() * allAbilities.length)].num, nature: Math.floor(Math.random() * 25) };
        });
        await send("player.ui.events", player, { event: "team_save", player_id: player, session_id: sessionId, data: { team_name: ["晴天队", "雨天队", "沙暴队", "龙队", "平衡队", "空间队", "强化队"][Math.floor(Math.random() * 7)], pokemon_count: team.length, pokemon: team } });
      }
      await new Promise(r => setTimeout(r, 3000 + Math.random() * 5000)); // 3-8s interval
    } catch (e) { /* retry */ }
  }
}

// ── Main ──
async function main() {
  await producer.connect();
  console.log(`Data daemon: ${BATTLE_WORKERS} battle + ${UI_WORKERS} UI workers → ${KAFKA_BROKER}`);

  // Connection test
  try {
    await send("battle.logs", "ping", { event: "daemon_start", data: { workers: { battle: BATTLE_WORKERS, ui: UI_WORKERS } } });
    console.log("Kafka connection OK");
  } catch (e) {
    console.error("Kafka connection FAILED:", e.message);
  }

  const workers = [];
  for (let i = 0; i < BATTLE_WORKERS; i++) workers.push(battleWorker(i + 1));
  for (let i = 0; i < UI_WORKERS; i++) workers.push(uiWorker(i + 1));

  // Heartbeat with stats (every 10s)
  let uptime = 0;
  setInterval(() => {
    uptime += 10;
    process.stdout.write(`\r[${uptime}s] battles:${battleCount} ui:${uiCount}  workers:${BATTLE_WORKERS}b+${UI_WORKERS}u  `);
  }, 10000);

  await Promise.all(workers);
}

main().catch(e => { console.error(e); process.exit(1); });
